version: "2"

services:
  nginx:
    image: nginx
    container_name: nginx
    network_mode: bridge
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d

  dockergen:
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    environment:
      - VIRTUAL_HOST=npm.hiqbattery.cn
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
  nginx-agent:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=agent.hiqbattery.cn
     
